# Generated by Django 3.2.6 on 2021-08-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='selling_option',
            field=models.CharField(choices=[('EVEN', 'Even'), ('ALL_TOGETHER', 'All together'), ('AVOID_ONE', 'Avoid one')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('PAID', 'Paid'), ('PARTIALLY_PAID', 'Partially paid'), ('FAILED', 'Failed')], default='OPEN', max_length=64),
        ),
    ]
