# Generated by Django 3.2.6 on 2021-08-15 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.reservation')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.ticket')),
            ],
        ),
    ]
