# Generated by Django 3.2.6 on 2021-08-15 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_remove_ticket_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='date',
            new_name='date_created',
        ),
    ]
