# Generated by Django 3.2.6 on 2021-08-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_rename_date_reservation_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='seat_number',
            field=models.IntegerField(),
        ),
    ]
